//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamboScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefinitionOfDone
    {
        public DefinitionOfDone()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int definition_of_done_id { get; set; }
        public string definition_of_done_source { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
    }
}
