//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamboScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int meeting_id { get; set; }
        public int meeting_type_id { get; set; }
        public int sprint_id { get; set; }
        public System.DateTime start_time { get; set; }
    
        public virtual MeetingType MeetingType { get; set; }
        public virtual Sprint Sprint { get; set; }
    }
}
