//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamboScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingType
    {
        public MeetingType()
        {
            this.Meetings = new HashSet<Meeting>();
        }
    
        public int meeting_type_id { get; set; }
        public string meeting_type_name { get; set; }
    
        public virtual ICollection<Meeting> Meetings { get; set; }
    }
}
