//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamboScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBLItem
    {
        public PBLItem()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int pbl_item_id { get; set; }
        public int project_id { get; set; }
        public Nullable<int> sprint_id { get; set; }
        public int status_id { get; set; }
        public int item_priority { get; set; }
        public decimal estimated_hours { get; set; }
        public string name { get; set; }
        public string item_description { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Sprint Sprint { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
