//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamboScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.ProjectRoleAssignments = new HashSet<ProjectRoleAssignment>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int person_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<ProjectRoleAssignment> ProjectRoleAssignments { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
