//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamboScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRoleAssignment
    {
        public int project_id { get; set; }
        public int person_id { get; set; }
        public int scrum_role_type_id { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Project Project { get; set; }
        public virtual ScrumRoleType ScrumRoleType { get; set; }
    }
}
