//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamboScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprint
    {
        public Sprint()
        {
            this.Meetings = new HashSet<Meeting>();
            this.PBLItems = new HashSet<PBLItem>();
        }
    
        public int sprint_id { get; set; }
        public string sprint_name { get; set; }
        public int project_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual ICollection<Meeting> Meetings { get; set; }
        public virtual ICollection<PBLItem> PBLItems { get; set; }
        public virtual Project Project { get; set; }
    }
}
