//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamboScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.PBLItems = new HashSet<PBLItem>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int status_id { get; set; }
        public string status1 { get; set; }
    
        public virtual ICollection<PBLItem> PBLItems { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
