//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamboScrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int task_id { get; set; }
        public string name { get; set; }
        public string task_description { get; set; }
        public decimal estimated_hours { get; set; }
        public int task_priority { get; set; }
        public int pbl_item_id { get; set; }
        public int status_id { get; set; }
        public Nullable<int> person_id { get; set; }
        public System.DateTime assignment_date { get; set; }
        public System.DateTime completion_date { get; set; }
    
        public virtual PBLItem PBLItem { get; set; }
        public virtual Person Person { get; set; }
        public virtual Status Status { get; set; }
    }
}
